import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import os

def load_data(filepath="scored_members_dashboard_feed.csv"):
    """
    Loads the scored dataset generated by the XGBoost Risk Model.
    This data contains the historical spend, demographic factors, and future risk probabilities
    necessary for accurate K-Means clustering.
    """
    if not os.path.exists(filepath):
        # Fallback to the synthetic claims data if the risk model feed isn't available
        if os.path.exists("sql_synthetic_claims.csv"):
            filepath = "sql_synthetic_claims.csv"
        else:
            raise FileNotFoundError(f"Missing {filepath}. Please run risk_model.py first to generate the base cohort.")
    
    return pd.read_csv(filepath)

def train_clustering_model(df: pd.DataFrame):
    """
    Implements High-Cost Claimant Pattern Recognition using PCA and K-Means Clustering.
    
    This function groups members into distinct "Risk Personas" to help U.S. employers
    tailor broad wellness initiatives rather than just targeting individuals. 
    This demonstrates the transition from reactive care to population health management.
    """
    print("\n[Architecture] Initializing Population Risk Segmentation (PCA & K-Means)...")
    
    # 1. Feature Selection
    # We select key clinical and financial indicators for the clustering algorithm
    cluster_features = [
        'Patient_age', 
        'Claim_total_target_12M', 
        'extension_chronic_burden_score',
        'extension_spend_velocity_ratio'
    ]
    
    # If Risk_Probability exists from the XGBoost model, we include it
    if 'Risk_Probability' in df.columns:
        cluster_features.append('Risk_Probability')
        
    X = df[cluster_features].fillna(0)
    
    # 2. Standardization
    # K-Means is distance-based, so features must be scaled to zero mean and unit variance
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 3. Principal Component Analysis (PCA)
    # Reducing high-dimensional clinical data into two components for visualization
    print("--> Applying Principal Component Analysis (PCA) for dimensionality reduction...")
    pca = PCA(n_components=2, random_state=42)
    X_pca = pca.fit_transform(X_scaled)
    
    # Storing PCA components for the Streamlit scatter plot
    df['PCA_Component_1'] = X_pca[:, 0]
    df['PCA_Component_2'] = X_pca[:, 1]
    
    # 4. K-Means Clustering
    # Segmenting the population into 4 actionable clinical tiers
    print("--> Executing K-Means Clustering to identify distinct patient risk personas...")
    n_clusters = 4
    kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    df['Cluster_ID'] = kmeans.fit_predict(X_scaled)
    
    # 5. Persona Mapping (Dynamic Business Logic)
    # We sort the clusters by their average Target Spend to dynamically name the personas
    cluster_summary = df.groupby('Cluster_ID')[['Claim_total_target_12M']].mean().reset_index()
    cluster_summary = cluster_summary.sort_values(by='Claim_total_target_12M')
    
    persona_names = {
        cluster_summary.iloc[0]['Cluster_ID']: "Low-Risk Baseline",
        cluster_summary.iloc[1]['Cluster_ID']: "Emerging Acute Risk",
        cluster_summary.iloc[2]['Cluster_ID']: "Chronic Condition Management",
        cluster_summary.iloc[3]['Cluster_ID']: "Catastrophic Multi-Morbidity"
    }
    
    df['Risk_Persona'] = df['Cluster_ID'].map(persona_names)
    
    print("\n[Model Results] Population Risk Personas Identified:")
    for k, v in persona_names.items():
        count = len(df[df['Cluster_ID'] == k])
        avg_spend = df[df['Cluster_ID'] == k]['Claim_total_target_12M'].mean()
        print(f"  - {v}: {count} members | Avg Projected Spend: ${avg_spend:,.2f}")

    return df

if __name__ == "__main__":
    try:
        print("Loading Population Dataset...")
        df_input = load_data()
        
        # Execute the PCA & K-Means Pipeline
        df_clustered = train_clustering_model(df_input)
        
        # Persist the clustered data so the Streamlit UI can render the 'Risk Persona' charts
        output_file = "clustered_patient_personas.csv"
        df_clustered.to_csv(output_file, index=False)
        
        print(f"\nSuccess: Population risk segmentation complete. Data saved to '{output_file}'.")
        
    except Exception as e:
        print(f"System Error in Clustering Module: {e}")
