import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression, PoissonRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import os

def load_population_data(filepath="scored_members_dashboard_feed.csv"):
    """
    Loads the scored member dataset. This data serves as the baseline for 
    the behavioral economics simulation.
    
    """
    if not os.path.exists(filepath):
        # Fallback to the synthetic claims data if the risk model feed isn't available
        if os.path.exists("sql_synthetic_claims.csv"):
            filepath = "sql_synthetic_claims.csv"
        else:
            raise FileNotFoundError(f"Missing {filepath}. Please run risk_model.py first.")
    
    df = pd.read_csv(filepath)
    
    # --- SYNTHETIC BEHAVIORAL FEATURE INJECTION ---
    # We ensure plan design variables are present for the simulation logic.
    np.random.seed(42)
    
    # Current Plan Design Features
    if 'Current_Deductible' not in df.columns:
        df['Current_Deductible'] = np.random.choice([1500, 2000, 3000], size=len(df))
    
    if 'PCP_Copay' not in df.columns:
        df['PCP_Copay'] = np.random.choice([20, 30, 50], size=len(df))
        
    # Behavioral Targets (Visit Counts & High Utilization Flags)
    if 'Annual_ER_Visits' not in df.columns:
        # Poisson distribution logic: high-risk members have higher expected visit rates
        risk_score = df.get('Risk_Probability', df.get('extension_chronic_burden_score', 0) / 5.0)
        base_rate = np.clip(risk_score * 2.0, 0.1, 5.0)
        df['Annual_ER_Visits'] = np.random.poisson(lam=base_rate, size=len(df))
        
    if 'High_Utilization_Flag' not in df.columns:
        # Binary target for Logistic Regression (e.g., > 2 visits per year)
        df['High_Utilization_Flag'] = np.where(df['Annual_ER_Visits'] >= 2, 1, 0)
        
    return df

def train_plan_simulator(df: pd.DataFrame):
    """
    Trains the simulation engine using two distinct mathematical approaches:
    1. Logistic Regression: To determine the probability of a member becoming a high-utilizer.
    2. Poisson Regressor (GLM): To predict the discrete count of clinical encounters.
    """
    print("\n[Architecture] Initializing Behavioral Economics Simulator (GLM & Logistic)...")
    
    # Features: Demographics + Clinical Risk + Plan Design
    features = ['Patient_age', 'extension_chronic_burden_score', 'Current_Deductible', 'PCP_Copay']
    
    # Include Risk_Probability if generated by the XGBoost model
    if 'Risk_Probability' in df.columns:
        features.append('Risk_Probability')
    
    X = df[features].fillna(0)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    
    # 1. Logistic Regression: Threshold Likelihood
    print("--> Training Logistic Regression for utilization threshold analysis...")
    y_logistic = df['High_Utilization_Flag']
    log_reg = LogisticRegression(random_state=42, class_weight='balanced')
    log_reg.fit(X_scaled, y_logistic)
    
    # 2. GLM (Poisson): Discrete Visit Forecasting
    print("--> Training Poisson Regressor (GLM) for encounter volume simulation...")
    y_poisson = df['Annual_ER_Visits']
    glm_poisson = PoissonRegressor(alpha=1e-4, max_iter=1000)
    glm_poisson.fit(X_scaled, y_poisson)
    
    return log_reg, glm_poisson, scaler, features

def simulate_plan_change(df: pd.DataFrame, glm_model, scaler, features, deductible_increase=500):
    """
    Simulates a 'What-If' scenario: What happens to utilization if we raise deductibles?
    
    This demonstrates the platform's ability to help U.S. employers 'bend the cost curve'
    by adjusting plan variables and forecasting the financial result.
    """
    print(f"\n[Simulation] Evaluating Scenario: +${deductible_increase} Deductible Increase...")
    
    # Create the 'Proposed' state
    df_sim = df.copy()
    df_sim['Proposed_Deductible'] = df_sim['Current_Deductible'] + deductible_increase
    
    # Baseline Predictions
    X_current = scaler.transform(df[features].fillna(0))
    current_visits = glm_model.predict(X_current)
    
    # Proposed Predictions
    sim_features_df = df[features].copy()
    sim_features_df['Current_Deductible'] = df_sim['Proposed_Deductible']
    X_proposed = scaler.transform(sim_features_df.fillna(0))
    proposed_visits = glm_model.predict(X_proposed)
    
    # Variance Analysis
    df_sim['Baseline_Visits'] = current_visits
    df_sim['Simulated_Visits'] = proposed_visits
    df_sim['Visit_Variance'] = df_sim['Simulated_Visits'] - df_sim['Baseline_Visits']
    
    # Financial Impact: Reclaiming capital for job creation
    # Avg cost per avoided non-emergent encounter = $1,200
    avg_cost = 1200
    df_sim['Simulated_Employer_Savings'] = (df_sim['Visit_Variance'] * -1) * avg_cost
    
    total_savings = df_sim['Simulated_Employer_Savings'].sum()
    print(f"--> Simulation Complete. Projected Gross Savings: ${total_savings:,.2f}")
    
    return df_sim

if __name__ == "__main__":
    try:
        print("Loading Population Baseline...")
        df_pop = load_population_data()
        
        # Train Simulator Logic
        log_reg, glm, scaler, feats = train_plan_simulator(df_pop)
        
        # Run a default $500 increase simulation
        df_final_sim = simulate_plan_change(df_pop, glm, scaler, feats, deductible_increase=500)
        
        # Save for UI
        output_file = "plan_simulation_results.csv"
        df_final_sim.to_csv(output_file, index=False)
        print(f"\nSuccess: Behavioral simulation data saved to '{output_file}'.")
        
    except Exception as e:
        print(f"System Error in Simulator Module: {e}")
