import pandas as pd
import numpy as np
import xgboost as xgb
import shap
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score, classification_report, average_precision_score
from sklearn.ensemble import GradientBoostingClassifier, RandomForestRegressor
import os
import google.generativeai as genai

# Standard attempt to import NLP fallback
try:
    from transformers import pipeline
except ImportError:
    pipeline = None

# Define the High-Cost Claimant (HCC) threshold ($50,000)
HCC_THRESHOLD = 50000.0

def load_and_prepare_data(filepath: str = "sql_synthetic_claims.csv") -> pd.DataFrame:
    """
    Loads the synthetic dataset generated by the CT-GAN engine and creates 
    the binary target variable (HCC Breach >= $50k) for the classification model.
    """
    if not os.path.exists(filepath):
        # Fallback to sample if the main generator hasn't been run locally
        if os.path.exists("fhir_synthetic_claims_sample.csv"):
            filepath = "fhir_synthetic_claims_sample.csv"
        else:
            raise FileNotFoundError(f"Could not find {filepath}. Please run synthetic_data.py first.")
        
    df = pd.read_csv(filepath)
    # Define binary classification target: 1 if spend exceeds $50k, 0 otherwise
    # In clinical data science, we focus on identifying the 'expensive' outliers.
    df['is_hcc_breach'] = (df['Claim_total_target_12M'] >= HCC_THRESHOLD).astype(int)
    return df

def train_xgboost_hcc_model(df: pd.DataFrame):
    """
    Trains an XGBoost model, tunes hyperparameters, extracts SHAP values, and
    generates Natural Language assessments for high-risk members.
    
    [USCIS EVIDENCE STRATEGY]:
    To prove technical feasibility and eliminate "Black Box" ambiguity, we utilize 
    SHAP (SHapley Additive exPlanations) to attribute precise mathematical weight 
    to individual clinical drivers.
    """
    # Exclude non-feature columns
    exclude_cols = [
        'Organization_name', 'Patient_identifier', 'Claim_createdDate', 
        'Claim_total_target_12M', 'extension_breached_50k', 'is_hcc_breach'
    ]
    features = [col for col in df.columns if col not in exclude_cols]
    
    X = df[features]
    y = df['is_hcc_breach']
    
    # Stratified split to maintain rare catastrophic claim ratio
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    
    # Calculate scale_pos_weight to handle imbalanced data (rare breaches)
    positive_cases = sum(y_train == 1)
    negative_cases = sum(y_train == 0)
    scale_pos_weight = negative_cases / positive_cases if positive_cases > 0 else 1.0
    
    print("\n[Architecture] Initiating XGBoost hyperparameter tuning (GridSearchCV)...")
    base_model = xgb.XGBClassifier(
        scale_pos_weight=scale_pos_weight,
        eval_metric='aucpr',
        random_state=42
    )
    
    param_grid = {
        'n_estimators': [100, 200],
        'max_depth': [3, 5],
        'learning_rate': [0.01, 0.05, 0.1],
        'subsample': [0.8, 1.0]
    }
    
    grid_search = GridSearchCV(estimator=base_model, param_grid=param_grid, scoring='average_precision', cv=3)
    grid_search.fit(X_train, y_train)
    
    model = grid_search.best_estimator_
    
    # Evaluate Model Performance
    y_pred_proba = model.predict_proba(X_test)[:, 1]
    auc_score = roc_auc_score(y_test, y_pred_proba)
    print(f"--> Training Complete. ROC-AUC Score: {auc_score:.4f}")
    
    # ---------------------------------------------------------
    # EXPLAINABLE AI (XAI): SHAP Values
    # ---------------------------------------------------------
    print("--> Calculating SHAP values for clinical explainability...")
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X)
    
    # Map the SHAP values back to the member rows
    top_drivers = []
    feature_names = X.columns
    
    for i in range(len(X)):
        # Find the feature that contributed most to the risk increase for this member
        sorted_indices = np.argsort(shap_values[i])[::-1]
        top_feature = feature_names[sorted_indices[0]]
        # Clean up the feature name for display
        clean_driver = top_feature.replace('extension_', '').replace('_', ' ').title()
        top_drivers.append(clean_driver)
    
    # ---------------------------------------------------------
    # GENERATIVE AI: Natural Language Clinical Narrative
    # ---------------------------------------------------------
    # Implement exponential backoff for API calls
    apiKey = "" # Empty string per system instructions
    
    # Prepare the scored dataframe
    df_scored = df.copy()
    df_scored['Risk_Probability'] = model.predict_proba(X)[:, 1]
    df_scored['Primary_Risk_Driver'] = top_drivers
    
    print("--> Generating GenAI Clinical Assessments...")
    
    # Simulated NLP Assessment for High Risk Members
    # In production, this would call the Gemini API
    assessments = []
    for i, row in df_scored.iterrows():
        if row['Risk_Probability'] >= 0.75:
            assessments.append(
                f"High-risk trajectory detected. Primary driver identified as '{row['Primary_Risk_Driver']}'. "
                f"Recommended Action: Immediate enrollment in proactive Care Management to intercept acute claims."
            )
        else:
            assessments.append("Standard monitoring. No immediate clinical intervention required.")
            
    df_scored['AI_Assessment'] = assessments
    
    return df_scored

if __name__ == "__main__":
    # Ensure local directory exists
    os.makedirs("src", exist_ok=True)
    
    try:
        df_raw = load_and_prepare_data("sql_synthetic_claims.csv")
        df_final = train_xgboost_hcc_model(df_raw)
        
        # Save for consumption by the Streamlit/HTML UI
        output_path = "scored_members_dashboard_feed.csv"
        df_final.to_csv(output_path, index=False)
        print(f"\nSuccess: Scored member data saved to {output_path}")
    except Exception as e:
        print(f"Error in Risk Model: {e}")
